/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace P2PTrading {
  export type OrderStruct = {
    orderId: BigNumberish;
    user: AddressLike;
    amount: BigNumberish;
    isBuyOrder: boolean;
    isCompleted: boolean;
    isApproved: boolean;
    timestamp: BigNumberish;
  };

  export type OrderStructOutput = [
    orderId: bigint,
    user: string,
    amount: bigint,
    isBuyOrder: boolean,
    isCompleted: boolean,
    isApproved: boolean,
    timestamp: bigint
  ] & {
    orderId: bigint;
    user: string;
    amount: bigint;
    isBuyOrder: boolean;
    isCompleted: boolean;
    isApproved: boolean;
    timestamp: bigint;
  };
}

export interface P2PTradingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "admin"
      | "approveOrder"
      | "authorizedAdmins"
      | "completeOrder"
      | "createBuyOrder"
      | "createSellOrder"
      | "getOrder"
      | "orderCounter"
      | "orders"
      | "usdtToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OrderApproved" | "OrderCompleted" | "OrderCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAdmins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBuyOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSellOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orderCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBuyOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSellOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "orderCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
}

export namespace OrderApprovedEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCompletedEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    isBuyOrder: boolean
  ];
  export type OutputTuple = [
    orderId: bigint,
    user: string,
    amount: bigint,
    isBuyOrder: boolean
  ];
  export interface OutputObject {
    orderId: bigint;
    user: string;
    amount: bigint;
    isBuyOrder: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface P2PTrading extends BaseContract {
  connect(runner?: ContractRunner | null): P2PTrading;
  waitForDeployment(): Promise<this>;

  interface: P2PTradingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  approveOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizedAdmins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  completeOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBuyOrder: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSellOrder: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [P2PTrading.OrderStructOutput],
    "view"
  >;

  orderCounter: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean, boolean, boolean, bigint] & {
        orderId: bigint;
        user: string;
        amount: bigint;
        isBuyOrder: boolean;
        isCompleted: boolean;
        isApproved: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveOrder"
  ): TypedContractMethod<[_orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedAdmins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "completeOrder"
  ): TypedContractMethod<[_orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBuyOrder"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSellOrder"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [_orderId: BigNumberish],
    [P2PTrading.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "orderCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean, boolean, boolean, bigint] & {
        orderId: bigint;
        user: string;
        amount: bigint;
        isBuyOrder: boolean;
        isCompleted: boolean;
        isApproved: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OrderApproved"
  ): TypedContractEvent<
    OrderApprovedEvent.InputTuple,
    OrderApprovedEvent.OutputTuple,
    OrderApprovedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCompleted"
  ): TypedContractEvent<
    OrderCompletedEvent.InputTuple,
    OrderCompletedEvent.OutputTuple,
    OrderCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;

  filters: {
    "OrderApproved(uint256)": TypedContractEvent<
      OrderApprovedEvent.InputTuple,
      OrderApprovedEvent.OutputTuple,
      OrderApprovedEvent.OutputObject
    >;
    OrderApproved: TypedContractEvent<
      OrderApprovedEvent.InputTuple,
      OrderApprovedEvent.OutputTuple,
      OrderApprovedEvent.OutputObject
    >;

    "OrderCompleted(uint256)": TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;
    OrderCompleted: TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;

    "OrderCreated(uint256,address,uint256,bool)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
  };
}
